from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from typing import Dict
import json
from ..agents.graph import agent_graph

router = APIRouter()

class ConnectionManager:
    def __init__(self):
        self.active_connections: Dict[str, WebSocket] = {}

    async def connect(self, websocket: WebSocket, client_id: str):
        await websocket.accept()
        self.active_connections[client_id] = websocket

    def disconnect(self, client_id: str):
        if client_id in self.active_connections:
            del self.active_connections[client_id]

    async def send_personal_message(self, message: dict, client_id: str):
        if client_id in self.active_connections:
            await self.active_connections[client_id].send_json(message)

manager = ConnectionManager()

@router.websocket("/ws/{client_id}")
async def websocket_endpoint(websocket: WebSocket, client_id: str):
    await manager.connect(websocket, client_id)
    try:
        while True:
            data = await websocket.receive_text()
            try:
                payload = json.loads(data)
                input_text = payload.get('command', '')
                
                # Execute LangGraph Workflow
                initial_state = {"input_text": input_text, "client_id": client_id}
                final_state = await agent_graph.ainvoke(initial_state)
                
                exec_result = final_state.get("execution_result", {})
                if exec_result and exec_result.get("client_execution_required"):
                    await manager.send_personal_message(
                        {
                            "type": "execute_plugin", 
                            "plugin": exec_result.get("plugin"), 
                            "params": exec_result.get("params")
                        },
                        client_id
                    )
                else:
                    response_text = final_state.get("final_response", "No response generated by the Orchestrator.")
                    await manager.send_personal_message(
                        {"type": "response", "content": response_text},
                        client_id
                    )
            except json.JSONDecodeError:
                await manager.send_personal_message(
                    {"type": "error", "content": "Invalid JSON format."},
                    client_id
                )
    except WebSocketDisconnect:
        manager.disconnect(client_id)
