from .state import AgentState

def formatter_node(state: AgentState):
    """
    Formats the execution results into a human-readable string.
    """
    # If a direct response was already generated by the planner
    if state.get("final_response"):
        return state
        
    result = state.get("execution_result")
    
    if result:
        if "error" in result:
            return {"final_response": f"Error: {result['error']}"}
        
        # Plugin-specific formatting (could also be delegated to the plugin itself in a real architecture)
        if state.get("selected_plugin") == "BatteryPlugin":
            level = result.get('level', 0)
            charging = result.get('charging', False)
            status = "charging" if charging else "on battery power"
            return {"final_response": f"Your device is currently at {level}% and is {status}."}
            
        return {"final_response": f"Executed successfully: {result}"}
        
    return {"final_response": "I'm sorry, I couldn't process that command or the plugin returned no data."}
